# Generated by Django 5.2.11 on 2026-06-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_first_n_ae97bb_idx',
            old_name='students_st_first__bcde10_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_last_na_6e3404_idx',
            old_name='students_st_last_na_a5883e_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_email_e271bc_idx',
            old_name='students_st_email_7581ac_idx',
        ),
    ]
